CREATE TYPE ratings AS ENUM (
    '1',
    '2',
    '3',
    '4',
    '5'
);

CREATE TABLE bookmark_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    rating ratings NOT NULL,
    content TEXT
);